/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ErrorRouteImport } from './routes/error'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as PublicPostsRouteRouteImport } from './routes/_public/posts/route'
import { Route as PublicPostsIndexRouteImport } from './routes/_public/posts/index'
import { Route as PublicPostsPostIdRouteImport } from './routes/_public/posts/$postId'

const ErrorRoute = ErrorRouteImport.update({
  id: '/error',
  path: '/error',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicPostsRouteRoute = PublicPostsRouteRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => PublicRoute,
} as any)
const PublicPostsIndexRoute = PublicPostsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicPostsRouteRoute,
} as any)
const PublicPostsPostIdRoute = PublicPostsPostIdRouteImport.update({
  id: '/$postId',
  path: '/$postId',
  getParentRoute: () => PublicPostsRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/error': typeof ErrorRoute
  '/posts': typeof PublicPostsRouteRouteWithChildren
  '/': typeof PublicIndexRoute
  '/posts/$postId': typeof PublicPostsPostIdRoute
  '/posts/': typeof PublicPostsIndexRoute
}
export interface FileRoutesByTo {
  '/error': typeof ErrorRoute
  '/': typeof PublicIndexRoute
  '/posts/$postId': typeof PublicPostsPostIdRoute
  '/posts': typeof PublicPostsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_protected': typeof ProtectedRoute
  '/_public': typeof PublicRouteWithChildren
  '/error': typeof ErrorRoute
  '/_public/posts': typeof PublicPostsRouteRouteWithChildren
  '/_public/': typeof PublicIndexRoute
  '/_public/posts/$postId': typeof PublicPostsPostIdRoute
  '/_public/posts/': typeof PublicPostsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/error' | '/posts' | '/' | '/posts/$postId' | '/posts/'
  fileRoutesByTo: FileRoutesByTo
  to: '/error' | '/' | '/posts/$postId' | '/posts'
  id:
    | '__root__'
    | '/_protected'
    | '/_public'
    | '/error'
    | '/_public/posts'
    | '/_public/'
    | '/_public/posts/$postId'
    | '/_public/posts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProtectedRoute: typeof ProtectedRoute
  PublicRoute: typeof PublicRouteWithChildren
  ErrorRoute: typeof ErrorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/error': {
      id: '/error'
      path: '/error'
      fullPath: '/error'
      preLoaderRoute: typeof ErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/posts': {
      id: '/_public/posts'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof PublicPostsRouteRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/posts/': {
      id: '/_public/posts/'
      path: '/'
      fullPath: '/posts/'
      preLoaderRoute: typeof PublicPostsIndexRouteImport
      parentRoute: typeof PublicPostsRouteRoute
    }
    '/_public/posts/$postId': {
      id: '/_public/posts/$postId'
      path: '/$postId'
      fullPath: '/posts/$postId'
      preLoaderRoute: typeof PublicPostsPostIdRouteImport
      parentRoute: typeof PublicPostsRouteRoute
    }
  }
}

interface PublicPostsRouteRouteChildren {
  PublicPostsPostIdRoute: typeof PublicPostsPostIdRoute
  PublicPostsIndexRoute: typeof PublicPostsIndexRoute
}

const PublicPostsRouteRouteChildren: PublicPostsRouteRouteChildren = {
  PublicPostsPostIdRoute: PublicPostsPostIdRoute,
  PublicPostsIndexRoute: PublicPostsIndexRoute,
}

const PublicPostsRouteRouteWithChildren =
  PublicPostsRouteRoute._addFileChildren(PublicPostsRouteRouteChildren)

interface PublicRouteChildren {
  PublicPostsRouteRoute: typeof PublicPostsRouteRouteWithChildren
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicPostsRouteRoute: PublicPostsRouteRouteWithChildren,
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ProtectedRoute: ProtectedRoute,
  PublicRoute: PublicRouteWithChildren,
  ErrorRoute: ErrorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
